// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for sqlserver metrics.
type MetricsConfig struct {
	SqlserverActiveTempTables                   MetricConfig `mapstructure:"sqlserver.active.temp.tables"`
	SqlserverBackupOrRestore                    MetricConfig `mapstructure:"sqlserver.backup_or_restore"`
	SqlserverBatchRequestRate                   MetricConfig `mapstructure:"sqlserver.batch.request.rate"`
	SqlserverBatchSQLCompilationRate            MetricConfig `mapstructure:"sqlserver.batch.sql_compilation.rate"`
	SqlserverBatchSQLRecompilationRate          MetricConfig `mapstructure:"sqlserver.batch.sql_recompilation.rate"`
	SqlserverDatabaseCount                      MetricConfig `mapstructure:"sqlserver.database.count"`
	SqlserverDatabaseIo                         MetricConfig `mapstructure:"sqlserver.database.io"`
	SqlserverDatabaseLatency                    MetricConfig `mapstructure:"sqlserver.database.latency"`
	SqlserverDatabaseOperations                 MetricConfig `mapstructure:"sqlserver.database.operations"`
	SqlserverDeadlocks                          MetricConfig `mapstructure:"sqlserver.deadlocks"`
	SqlserverExecutionErrors                    MetricConfig `mapstructure:"sqlserver.execution_errors"`
	SqlserverFreeListStalls                     MetricConfig `mapstructure:"sqlserver.free_list_stalls"`
	SqlserverFreeSpaceTempdb                    MetricConfig `mapstructure:"sqlserver.free_space_tempdb"`
	SqlserverFullScans                          MetricConfig `mapstructure:"sqlserver.full_scans"`
	SqlserverIndexSearches                      MetricConfig `mapstructure:"sqlserver.index_searches"`
	SqlserverLockWaitRate                       MetricConfig `mapstructure:"sqlserver.lock.wait.rate"`
	SqlserverLockWaitTimeAvg                    MetricConfig `mapstructure:"sqlserver.lock.wait_time.avg"`
	SqlserverLockTimeouts                       MetricConfig `mapstructure:"sqlserver.lock_timeouts"`
	SqlserverLogins                             MetricConfig `mapstructure:"sqlserver.logins"`
	SqlserverLogouts                            MetricConfig `mapstructure:"sqlserver.logouts"`
	SqlserverMemoryGrantsPending                MetricConfig `mapstructure:"sqlserver.memory_grants_pending"`
	SqlserverMirrorWriteTransaction             MetricConfig `mapstructure:"sqlserver.mirror_write_transaction"`
	SqlserverPageBufferCacheHitRatio            MetricConfig `mapstructure:"sqlserver.page.buffer_cache.hit_ratio"`
	SqlserverPageCheckpointFlushRate            MetricConfig `mapstructure:"sqlserver.page.checkpoint.flush.rate"`
	SqlserverPageLazyWriteRate                  MetricConfig `mapstructure:"sqlserver.page.lazy_write.rate"`
	SqlserverPageLifeExpectancy                 MetricConfig `mapstructure:"sqlserver.page.life_expectancy"`
	SqlserverPageOperationRate                  MetricConfig `mapstructure:"sqlserver.page.operation.rate"`
	SqlserverPageSplitRate                      MetricConfig `mapstructure:"sqlserver.page.split.rate"`
	SqlserverPageLookups                        MetricConfig `mapstructure:"sqlserver.page_lookups"`
	SqlserverProcessesBlocked                   MetricConfig `mapstructure:"sqlserver.processes.blocked"`
	SqlserverReplicaReceived                    MetricConfig `mapstructure:"sqlserver.replica_received"`
	SqlserverReplicaSent                        MetricConfig `mapstructure:"sqlserver.replica_sent"`
	SqlserverResourcePoolDiskThrottledReadRate  MetricConfig `mapstructure:"sqlserver.resource_pool.disk.throttled.read.rate"`
	SqlserverResourcePoolDiskThrottledWriteRate MetricConfig `mapstructure:"sqlserver.resource_pool.disk.throttled.write.rate"`
	SqlserverTransactionRate                    MetricConfig `mapstructure:"sqlserver.transaction.rate"`
	SqlserverTransactionWriteRate               MetricConfig `mapstructure:"sqlserver.transaction.write.rate"`
	SqlserverTransactionDelays                  MetricConfig `mapstructure:"sqlserver.transaction_delays"`
	SqlserverTransactionLogFlushDataRate        MetricConfig `mapstructure:"sqlserver.transaction_log.flush.data.rate"`
	SqlserverTransactionLogFlushRate            MetricConfig `mapstructure:"sqlserver.transaction_log.flush.rate"`
	SqlserverTransactionLogFlushWaitRate        MetricConfig `mapstructure:"sqlserver.transaction_log.flush.wait.rate"`
	SqlserverTransactionLogGrowthCount          MetricConfig `mapstructure:"sqlserver.transaction_log.growth.count"`
	SqlserverTransactionLogShrinkCount          MetricConfig `mapstructure:"sqlserver.transaction_log.shrink.count"`
	SqlserverTransactionLogUsage                MetricConfig `mapstructure:"sqlserver.transaction_log.usage"`
	SqlserverUsedMemory                         MetricConfig `mapstructure:"sqlserver.used_memory"`
	SqlserverUserConnectionCount                MetricConfig `mapstructure:"sqlserver.user.connection.count"`
	SqlserverVersionStoreSize                   MetricConfig `mapstructure:"sqlserver.version_store_size"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SqlserverActiveTempTables: MetricConfig{
			Enabled: false,
		},
		SqlserverBackupOrRestore: MetricConfig{
			Enabled: false,
		},
		SqlserverBatchRequestRate: MetricConfig{
			Enabled: true,
		},
		SqlserverBatchSQLCompilationRate: MetricConfig{
			Enabled: true,
		},
		SqlserverBatchSQLRecompilationRate: MetricConfig{
			Enabled: true,
		},
		SqlserverDatabaseCount: MetricConfig{
			Enabled: false,
		},
		SqlserverDatabaseIo: MetricConfig{
			Enabled: false,
		},
		SqlserverDatabaseLatency: MetricConfig{
			Enabled: false,
		},
		SqlserverDatabaseOperations: MetricConfig{
			Enabled: false,
		},
		SqlserverDeadlocks: MetricConfig{
			Enabled: false,
		},
		SqlserverExecutionErrors: MetricConfig{
			Enabled: false,
		},
		SqlserverFreeListStalls: MetricConfig{
			Enabled: false,
		},
		SqlserverFreeSpaceTempdb: MetricConfig{
			Enabled: false,
		},
		SqlserverFullScans: MetricConfig{
			Enabled: false,
		},
		SqlserverIndexSearches: MetricConfig{
			Enabled: false,
		},
		SqlserverLockWaitRate: MetricConfig{
			Enabled: true,
		},
		SqlserverLockWaitTimeAvg: MetricConfig{
			Enabled: true,
		},
		SqlserverLockTimeouts: MetricConfig{
			Enabled: false,
		},
		SqlserverLogins: MetricConfig{
			Enabled: false,
		},
		SqlserverLogouts: MetricConfig{
			Enabled: false,
		},
		SqlserverMemoryGrantsPending: MetricConfig{
			Enabled: false,
		},
		SqlserverMirrorWriteTransaction: MetricConfig{
			Enabled: false,
		},
		SqlserverPageBufferCacheHitRatio: MetricConfig{
			Enabled: true,
		},
		SqlserverPageCheckpointFlushRate: MetricConfig{
			Enabled: true,
		},
		SqlserverPageLazyWriteRate: MetricConfig{
			Enabled: true,
		},
		SqlserverPageLifeExpectancy: MetricConfig{
			Enabled: true,
		},
		SqlserverPageOperationRate: MetricConfig{
			Enabled: true,
		},
		SqlserverPageSplitRate: MetricConfig{
			Enabled: true,
		},
		SqlserverPageLookups: MetricConfig{
			Enabled: false,
		},
		SqlserverProcessesBlocked: MetricConfig{
			Enabled: false,
		},
		SqlserverReplicaReceived: MetricConfig{
			Enabled: false,
		},
		SqlserverReplicaSent: MetricConfig{
			Enabled: false,
		},
		SqlserverResourcePoolDiskThrottledReadRate: MetricConfig{
			Enabled: false,
		},
		SqlserverResourcePoolDiskThrottledWriteRate: MetricConfig{
			Enabled: false,
		},
		SqlserverTransactionRate: MetricConfig{
			Enabled: true,
		},
		SqlserverTransactionWriteRate: MetricConfig{
			Enabled: true,
		},
		SqlserverTransactionDelays: MetricConfig{
			Enabled: false,
		},
		SqlserverTransactionLogFlushDataRate: MetricConfig{
			Enabled: true,
		},
		SqlserverTransactionLogFlushRate: MetricConfig{
			Enabled: true,
		},
		SqlserverTransactionLogFlushWaitRate: MetricConfig{
			Enabled: true,
		},
		SqlserverTransactionLogGrowthCount: MetricConfig{
			Enabled: true,
		},
		SqlserverTransactionLogShrinkCount: MetricConfig{
			Enabled: true,
		},
		SqlserverTransactionLogUsage: MetricConfig{
			Enabled: true,
		},
		SqlserverUsedMemory: MetricConfig{
			Enabled: false,
		},
		SqlserverUserConnectionCount: MetricConfig{
			Enabled: true,
		},
		SqlserverVersionStoreSize: MetricConfig{
			Enabled: false,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for sqlserver resource attributes.
type ResourceAttributesConfig struct {
	SqlserverComputerName ResourceAttributeConfig `mapstructure:"sqlserver.computer.name"`
	SqlserverDatabaseName ResourceAttributeConfig `mapstructure:"sqlserver.database.name"`
	SqlserverInstanceName ResourceAttributeConfig `mapstructure:"sqlserver.instance.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		SqlserverComputerName: ResourceAttributeConfig{
			Enabled: false,
		},
		SqlserverDatabaseName: ResourceAttributeConfig{
			Enabled: true,
		},
		SqlserverInstanceName: ResourceAttributeConfig{
			Enabled: false,
		},
	}
}

// MetricsBuilderConfig is a configuration for sqlserver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
